#!/bin/bash
# shellcheck disable=SC1091

# Configurar firefox e instalar nuestras extensiones

[ "$(id -u)" -eq 0 ] && exit 1

source "$HOME/.dotfiles/assets/shell/shell-utils"

set +e

LOG_DIR=$(get_log_dir browser-config)
TMP_DIR=$(get_tmp_dir browser-config)

install() {
	PROFILES_INI="$BROWSER_DIR/installs.ini"

	get_profile() {
		# Obtiene el perfil predeterminado del archivo
		# profiles.ini después de ejecutar Firefox
		[ -f "$PROFILES_INI" ] &&
			grep -oP '^Default=\K.*' "$PROFILES_INI" | head -n1
	}

	makeuserjs() {
		# Añadir al perfil el user.js y user-overrides.js
		ARKENFOX="$PROFILE_DIR/arkenfox.js"
		OVERRIDES="$PROFILE_DIR/user-overrides.js"
		USERJS="$PROFILE_DIR/user.js"

		ln -sf "$HOME/.dotfiles/assets/configs/apps/firefox/user-overrides.js" \
			"$OVERRIDES"

		[ ! -f "$ARKENFOX" ] &&
			download "https://raw.githubusercontent.com/arkenfox/user.js/master/user.js" \
				"$ARKENFOX"

		cat "$ARKENFOX" "$OVERRIDES" >"$USERJS"
		chown "$USER:wheel" "$ARKENFOX" "$USERJS"
	}

	installffaddons() {
		# Lista con el nombre de las extensiones a instalar
		# Puedes encontrarlo en la tienda de Firefox como:
		# https://addons.mozilla.org/.../Firefox/addon/NOMBRE_EXTENSIÓN/...
		ADDON_LIST=(
			"checkmarks-web-ext"
			"clearurls"
			"darkreader"
			"istilldontcareaboutcookies"
			"keepassxc-browser"
			"sponsorblock"
			"ublock-origin"
			"violentmonkey"
		)

		mkdir -p "$PROFILE_DIR/extensions/"

		echo "Descargando extensiones..."
		# Para cada addon de la lista descargamos la extensión y la movemos
		# dentro de nuestro perfil de Firefox
		for ADDON in "${ADDON_LIST[@]}"; do
			ADDON_URL=$(
				curl --silent "https://addons.mozilla.org/en-US/firefox/addon/${ADDON}/" |
					grep -o 'https://addons.mozilla.org/firefox/downloads/file/[^"]*'
			)

			# El nombre del addon es la última parte de la URL
			FILE="${ADDON_URL##*/}"

			# Descargamos el addon en el directorio temporal
			echo "Descargando $ADDON..."
			wget -q "$ADDON_URL" -O "$TMP_DIR/$FILE" 2>/dev/null

			# Extraemos el id de la extensión desde el archivo manifest.json
			# (El addon debe guardarse en el perfil como ID.xpi)
			ID="$(unzip -p "$TMP_DIR/$FILE" manifest.json | grep "\"id\"" | head -n 1)"
			ID="${ID%\"*}"
			ID="${ID##*\"}"

			# El ID aveces no se puede extraer para checkmarks-web-ext, lo
			# establecemos manualmente en esos casos
			[ -z "$ID" ] && [ "$ADDON" = "checkmarks-web-ext" ] &&
				ID="{bd97f89b-17ba-4539-9fec-06852d07f917}"

			# Si se pudo extraer el ID, guardamos el addon en el perfil
			if [ -n "$ID" ]; then
				mv "$TMP_DIR/$FILE" "$PROFILE_DIR/extensions/$ID.xpi" 2>/dev/null
			fi
		done
		echo "¡Listo! Extensiones descargadas"

		chown -R "$USER:$USER" "$PROFILE_DIR/extensions"
	}

	installtheme() {
		mkdir -p "$PROFILE_DIR/chrome/"
		ln -fs "$HOME/.dotfiles/assets/configs/apps/firefox/userChrome.css" "$PROFILE_DIR"/chrome/
	}

	# Ejecutar en modo headless para generar un perfil predeterminado
	[ ! -f "$PROFILES_INI" ] &&
		for ((i = 1; i <= 3; i++)); do
			if [ -f /usr/bin/firefox ] && echo "$BROWSER_DIR" | grep -qi "firefox"; then
				echo "(intento: $i) Ejecutando Firefox"
				MOZ_LOG_FILE="$LOG_DIR/firefox.log" \
					timeout -k 2s 10s /usr/bin/firefox --headless >/dev/null 2>&1 || true
			fi

			if [ -f /usr/bin/librewolf ] && echo "$BROWSER_DIR" | grep -qi "librewolf" &&
				[ ! -f "$PROFILES_INI" ]; then
				echo "(intento: $i) Ejecutando LibreWolf"
				MOZ_LOG_FILE="$LOG_DIR/librewolf.log" \
					timeout -k 2s 10s /usr/bin/librewolf --headless >/dev/null 2>&1 || true
			fi

			if [ -f "$PROFILES_INI" ]; then
				echo "(intento: $i) perfil predeterminado encontrado"
				break
			fi
		done

	if [ ! -f "$PROFILES_INI" ]; then
		echo "Error al crear el perfil predeterminado en $BROWSER_DIR"
		return
	fi

	# Nos salimos si no se puedo obtener un perfil de usuario válido
	if ! PROFILE=$(get_profile) && [ -n "$PROFILE" ]; then
		echo "Error al obtener el perfil predeterminado desde $PROFILES_INI"
		return
	fi

	PROFILE_DIR="$BROWSER_DIR/$PROFILE"

	makeuserjs
	installffaddons
	installtheme
}

BROWSER_DIR="$HOME/.config/mozilla/firefox"
install
BROWSER_DIR="$HOME/.mozilla/firefox"
install
BROWSER_DIR="$HOME/.config/librewolf/librewolf"
install
