#!/bin/bash
# shellcheck disable=SC1091

# Configurar firefox e instalar nuestras extensiones

[ "$(id -u)" -eq 0 ] && exit 1

source "$HOME/.dotfiles/assets/shell/shell-utils"

set +e

BROWSER_DIR="$HOME/.config/mozilla/firefox"
PROFILES_INI="$BROWSER_DIR/profiles.ini"

LOG_DIR=$(init_log firefox-config)
TMP_DIR=$(get_tmp firefox-config)

get_profile() {
	# Obtiene el perfil predeterminado del archivo
	# profiles.ini después de ejecutar Firefox
	grep -oP "Default=\K.*" "$PROFILES_INI" | head -n1
}

makeuserjs() {
	# Añadir al perfil el user.js y user-overrides.js
	ARKENFOX="$PROFILE_DIR/arkenfox.js"
	OVERRIDES="$PROFILE_DIR/user-overrides.js"
	USERJS="$PROFILE_DIR/user.js"

	ln -sf "$HOME/.dotfiles/assets/configs/apps/firefox/user-overrides.js" \
		"$OVERRIDES"

	[ ! -f "$ARKENFOX" ] &&
		download "https://raw.githubusercontent.com/arkenfox/user.js/master/user.js" \
			"$ARKENFOX"

	cat "$ARKENFOX" "$OVERRIDES" >"$USERJS"
	chown "$USER:wheel" "$ARKENFOX" "$USERJS"
}

installffaddons() {
	# Lista con el nombre de las extensiones a instalar
	# Puedes encontrarlo en la tienda de Firefox como:
	# https://addons.mozilla.org/.../Firefox/addon/NOMBRE_EXTENSIÓN/...
	ADDON_LIST=(
		"checkmarks-web-ext"
		"clearurls"
		"darkreader"
		"decentraleyes"
		"enlight"
		"istilldontcareaboutcookies"
		"keepassxc-browser"
		"sponsorblock"
		"ublock-origin"
		"violentmonkey"
		"xbs"
	)

	mkdir -p "$PROFILE_DIR/extensions/"

	# Para cada addon de la lista descargamos la extensión y la movemos
	# dentro de nuestro perfil de Firefox
	for ADDON in "${ADDON_LIST[@]}"; do
		# Si es ublock-origin, descargamos el addon desde GitHub
		if [ "$ADDON" == "ublock-origin" ]; then
			ADDON_URL=$(
				curl -sL "https://api.github.com/repos/gorhill/uBlock/releases/latest" |
					grep -E 'browser_download_url.*firefox' | cut -d '"' -f 4
			)
		# Para todos los demás, los descargamos desde la tienda
		else
			ADDON_URL=$(
				curl --silent "https://addons.mozilla.org/en-US/firefox/addon/${ADDON}/" |
					grep -o 'https://addons.mozilla.org/firefox/downloads/file/[^"]*'
			)
		fi

		# El nombre del addon es la última parte de la URL
		FILE="${ADDON_URL##*/}"

		# Descargamos el addon en el directorio temporal
		wget -q "$ADDON_URL" -O "$TMP_DIR/$FILE"

		# Extraemos el id de la extensión desde el archivo manifest.json
		# (El addon debe guardarse en el perfil como ID.xpi)
		ID="$(unzip -p "$TMP_DIR/$FILE" manifest.json | grep "\"id\"" | head -n 1)"
		ID="${ID%\"*}"
		ID="${ID##*\"}"

		# El ID aveces no se puede extraer para checkmarks-web-ext, lo
		# establecemos manualmente en esos casos
		[ -z "$ID" ] && [ "$ADDON" = "checkmarks-web-ext" ] &&
			ID="{bd97f89b-17ba-4539-9fec-06852d07f917}"

		# Si se pudo extraer el ID, guardamos el addon en el perfil
		if [ -n "$ID" ]; then
			mv "$TMP_DIR/$FILE" "$PROFILE_DIR/extensions/$ID.xpi"
		fi
	done

	chown -R "$USER:$USER" "$PROFILE_DIR/extensions"
}

installtheme() {
	mkdir -p "$PROFILE_DIR/chrome/"
	ln -fs "$HOME/.dotfiles/assets/configs/apps/firefox/userChrome.css" "$PROFILE_DIR"/chrome/
}

# Ejecutar Firefox en modo headless para generar un perfil predeterminado
for ((i = 1; i <= 3; i++)); do
	export MOZ_LOG_FILE="$LOG_DIR/firefox.log"
	timeout -k 25s 5s firefox --headless 2>&1 || true
	[ -d "$BROWSER_DIR" ] && break
	log "(intento: $i) firefox no pudo iniciarse"
	sleep 5
done

# Nos salimos si no se puedo obtener un perfil de usuario
PROFILE=$(get_profile) || exit 1
PROFILE_DIR="$BROWSER_DIR/$PROFILE"

makeuserjs
installffaddons
installtheme
