#!/bin/bash

# Script para auto-configurar TauonMusicBox
# https://github.com/Taiko2k/TauonMusicBox

[ "$(id -u)" -eq 0 ] && exit 1

source "$HOME/.dotfiles/assets/shell/shell-utils"

set +e

APP_DIR="$HOME/.local/share/TauonMusicBox"
CONF="$APP_DIR/tauon.conf"
BASE_FONT="Fira Sans Condensed"

install_themes() {
	ensure_dir "$APP_DIR/theme/" >/dev/null
	aunpack "$HOME/.dotfiles/assets/themes.tar.gz" \
		-X "$APP_DIR/theme/" >/dev/null
}

modify_config() {
	sed -i \
		-e 's/use-custom-fonts = false/use-custom-fonts = true/' \
		-e "s/font-main-standard = \".*\"/font-main-standard = \"$BASE_FONT\"/" \
		-e "s/font-main-medium = \".*\"/font-main-medium = \"$BASE_FONT Medium\"/" \
		-e "s/font-main-bold = \".*\"/font-main-bold = \"$BASE_FONT Bold\"/" \
		-e "s/font-main-condensed = \".*\"/font-main-condensed = \"$BASE_FONT\"/" \
		-e "s/font-main-condensed-bold = \".*\"/font-main-condensed-bold = \"$BASE_FONT Bold\"/" \
		-e 's/auto-dl-artist-data = false/auto-dl-artist-data = true/' \
		-e 's/auto-update-playlists = false/auto-update-playlists = true/' \
		-e 's/auto-search-lyrics = false/auto-search-lyrics = true/' \
		-e 's/restore-window-position = true/restore-window-position = false/' \
		-e 's/theme-name = ".*"/theme-name = "aleister-gruvbox"/' \
		"$CONF"
}

rm -f "$CONF"

# Iniciamos tauon para que se cree el archivo de configuración
for ((i = 1; i <= 4; i++)); do
	XDG_SESSION_TYPE=x11 tauon >/dev/null 2>&1 &
	sleep 10
	pkill tauonmb
	[ -e "$CONF" ] && break
	log "(intento $i) tauon no pudo iniciarse"
	rm -rf "$APP_DIR"
done

[ ! -e "$CONF" ] && exit 1

install_themes
modify_config
