#!/bin/bash

# Script para configurar libvirt de forma que nuestro usuario pueda usar
# virt-manager sin tener que introducir la contraseña cada vez

[ "$(id -u)" -eq 0 ] && exit 1

# Instalar y configurar libvirt
virt_install() {
	xargs yay -S --noconfirm --disable-download-timeout --needed \
		<"$HOME/.dotfiles/assets/packages/opt/virt"

	sudo /usr/bin/cp "$HOME/.dotfiles/assets/desktop/looking-glass-client.desktop" \
		/usr/local/share/applications/looking-glass-client.desktop
	sudo /usr/bin/chmod 644 /usr/local/share/applications/looking-glass-client.desktop

	# Configurar QEMU para usar el usuario actual
	sudo /usr/bin/sed -i "s/^#user = .*/user = \"$USER\"/" /etc/libvirt/qemu.conf
	sudo /usr/bin/sed -i "s/^#group = .*/group = \"$USER\"/" /etc/libvirt/qemu.conf

	# Configurar libvirt
	sudo /usr/bin/sed -i "s/^#unix_sock_group = .*/unix_sock_group = \"$USER\"/" \
		/etc/libvirt/libvirtd.conf
	sudo /usr/bin/sed -i "s/^#unix_sock_rw_perms = .*/unix_sock_rw_perms = \"0770\"/" \
		/etc/libvirt/libvirtd.conf

	# Agregar el usuario a los grupos necesarios para la virtualización
	sudo /usr/bin/usermod -aG libvirt "$USER"
	sudo /usr/bin/usermod -aG libvirt-qemu "$USER"
	sudo /usr/bin/usermod -aG kvm "$USER"

	# Activar los servicios necesarios
	sudo /usr/bin/systemctl enable libvirtd
	sudo /usr/bin/systemctl enable virtlogd
}

# Desinstalar libvirt por completo
virt_uninstall() {
	sudo /usr/bin/systemctl disable libvirtd --now
	sudo /usr/bin/systemctl disable virtlogd --now

	# Borrar al usuario de los grupos
	for GROUP in libvirt libvirt-qemu kvm; do
		sudo /usr/bin/gpasswd -d "$USER" $GROUP
	done

	# Desinstalar los paquetes
	xargs yay -Rcns --noconfirm \
		<"$HOME/.dotfiles/assets/packages/opt/virt"

	# Borrar archivos restantes
	sudo /usr/bin/rm -rf /var/lib/libvirt
	sudo /usr/bin/rm -rf /etc/libvirt
	sudo /usr/bin/rm -f /usr/local/share/applications/looking-glass-client.desktop

	sync
}

if [ "$1" = "uninstall" ]; then
	virt_uninstall >/dev/null 2>&1
else
	virt_install
fi
