onboarding = false

[theme]
name = "gruvbox"

[terminal]
default_shell = "/bin/zsh"

[update]

[keys]

[ui]
sidebar_width = 18
pane_gaps = false

[experimental]
kitty_graphics = true
pane_history = false

[advanced]
scrollback_limit_bytes = 5000000
