#!/bin/sh

. "$HOME/.dotfiles/assets/shell/shell-utils-sh"

alias grub-update='sudo /usr/bin/grub-mkconfig -o /boot/grub/grub.cfg'

alias clipboard="wl-copy"
alias webcam="ffplay /dev/video0"

alias vi='nvim'
alias vim='nvim'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias cp='cp -iv'
alias cat='bat -p --tabs 8'
alias ls='eza -lagX --time-style iso --group-directories-first --smart-group'
alias grep='grep --color=auto'
alias tree='exa --tree'

alias xdotool_table='xmodmap -pk'
alias find_broken_links='find / -xtype l -print 2>/dev/null'
alias rebuild_detector="checkrebuild -v"

# Pacman
#-------------------------------------------------------------------------------

update() {
	yay -Syuu --sudoloop --answerclean --answerdiff --removemake
	~/.dotfiles/updater/nix-conf -d
}

deepcleanup() {
	yay -Ycc --noconfirm
	yay -Scc --noconfirm
	sudo /usr/bin/paccache -rk1
}

# Función para restaurar los paquetes
# instalados explícitamente como tales
reexplicit() {
	for PACKAGE in $(yay -Qq); do
		if grep -E "\[ALPM\] installed" /var/log/pacman.log |
			grep "$PACKAGE" >/dev/null 2>&1; then
			sudo /usr/bin/pacman -D --asexplicit "$PACKAGE"
		fi
	done
}

reinstall() {
	# shellcheck disable=SC2046
	yay -S $(pacman -Qq | grep -v "$(pacman -Qqm)")
}

pac_find() {
	# Buscar archivos .pacnew y .pacsave
	sudo /usr/bin/find /etc \
		\( -name "*.pacnew" -o -name "*.pacsave" \) 2>/dev/null | while read -r _file; do
		# Obtener el nombre del archivo original
		_og_file="${_file%.pacnew}"
		_og_file="${_og_file%.pacsave}"

		# Mostrar encabezado
		echo "##$(printf '#%.0s' $(seq 1 ${#_og_file}))##"
		echo "# $_og_file #"
		echo "##$(printf '#%.0s' $(seq 1 ${#_og_file}))##"

		# Mostrar diferencias y limitar la salida
		sudo /usr/bin/diff -d "$_file" "$_og_file" | head -n 20
	done
}

GCC() {
	gcc "$1" -o "${1%.*}"
}

du() {
	{
		BLOCKSIZE="$(echo "2^30" | bc)" # GiB
		export BLOCKSIZE
		/usr/bin/du -s -- *
		/usr/bin/du -s -- .*
	} 2>/dev/null | sort -rnk 1
}

reduce_pdf() {
	gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 \
		-dPDFSETTINGS=/screen \
		-dDownsampleColorImages=true \
		-dColorImageResolution=137 \
		-dDownsampleGrayImages=true \
		-dGrayImageResolution=137 \
		-dDownsampleMonoImages=true \
		-dMonoImageResolution=137 \
		-dNOPAUSE -dBATCH -dQUIET \
		-sOutputFile="${1%.*} (Reduced).pdf" "$1"
}

#-------------------------------------------------------------------------------

filetype() {
	cat <<-EOF
		xdg-mime: $(xdg-mime query filetype "$1")
		file:     $(file --dereference --brief --mime-type "$1")
	EOF
}

pipewire_restart() {
	systemctl --user stop wireplumber
	systemctl --user stop pipewire-pulse
	systemctl --user stop pipewire
	systemctl --user start pipewire
	systemctl --user start pipewire-pulse
	systemctl --user start wireplumber
}

lrc_put() {
	~/.local/bin/lrcput -d "$1" -s -R -r
}

screen_record() {
	if [ -z "$1" ]; then
		echo "Se debe dar como argumento el archivo de salida" >&2
		return 1
	fi
	RESOLUTION=$(get_monitor_resolution)
	wf-recorder -g "$RESOLUTION" -a -f "$1"
}

yabridgectl_dirs() {
	[ -d "$WINEPREFIX/drive_c/Program Files/Common Files" ] &&
		yabridgectl add "$WINEPREFIX/drive_c/Program Files/Common Files"
	[ -d "$WINEPREFIX/drive_c/Program Files/Steinberg" ] &&
		yabridgectl add "$WINEPREFIX/drive_c/Program Files/Steinberg"
	yabridgectl sync --prune
}

# Coding
#-------------------------------------------------------------------------------

# Borrar entornos de un código laTeX
desencapsular() {
	_tag="$1"
	shift
	perl -pe "s/\\\\${_tag}\\{([^{}]*(?:\\{${_tag}\\}[^{}]*)*)\\}/\$1/g" "$@"
}

push() {
	# shellcheck disable=SC2086
	if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
		git add .
		eval $TERMINAL $REGULAR_OPTS $TERMEXEC \
			"sh -c \"cd $HOME/.dotfiles && git diff --cached\""
		git commit
		git push
	else
		echo "No estás dentro de ningún repositorio" >&2
	fi
}
