#!/bin/bash

# Script para establecer zsh como el shell de nuestro usuario e instalar los
# archivos de configuración

[ "$(id -u)" -eq 0 ] && exit 1

# Crear la carpeta ~/.config
mkdir -p "$HOME/.config"

# Instalar los archivos de configuración
"$HOME/.dotfiles/update.sh"

# Selecciona zsh como el shell del usuario
echo "ZDOTDIR=\$HOME/.config/zsh" | sudo /usr/bin/tee /etc/zsh/zshenv
sudo /usr/bin/chsh -s /bin/zsh "$USER"
