#!/bin/sh

# Script para compilar e instalar yay

[ "$(id -u)" -eq 0 ] && exit 1

TMP_DIR="/tmp/yay_install_temp"
mkdir -p "$TMP_DIR"
git clone --depth 1 https://aur.archlinux.org/yay.git "$TMP_DIR" >/dev/null
sh -c "cd $TMP_DIR && makepkg -si --noconfirm"
