#!/bin/bash

# Script para sustituir sudo por OpenDoas durante la instalación del SO

[ "$(id -u)" -ne 0 ] && exit 1

# Obtener el nombre de usuario con UID 1000 (generalmente el primer usuario no root)
RUSER="$(getent passwd 1000 | cut -d: -f1)"
if [ -z "$RUSER" ]; then
	echo "Error: No se pudo encontrar un usuario con UID 1000." >&2
	exit 1
fi

# Configurar OpenDoas
echo "Configurando OpenDoas..."
cat <<EOF | tee /etc/doas.conf
permit persist keepenv setenv { SUDO_USER SUDO_UID SUDO_GID LANG LC_ALL } :wheel

permit nopass 1000 as root cmd /usr/bin/rm
permit nopass 1000 as root cmd /usr/bin/cp
permit nopass 1000 as root cmd /usr/bin/chmod
permit nopass 1000 as root cmd /usr/bin/tee
permit nopass 1000 as root cmd /usr/bin/pacman
permit nopass 1000 as root cmd /usr/bin/usermod
permit nopass 1000 as root cmd /usr/bin/gpasswd
permit nopass 1000 as root cmd /usr/bin/chsh
permit nopass 1000 as root cmd /usr/bin/systemctl

permit nopass 1000 as root cmd /usr/bin/sed
permit nopass 1000 as root cmd /usr/bin/umount
permit nopass 1000 as root cmd /usr/local/bin/wakeat

permit nopass 1000 as root cmd /usr/bin/rfkill args unblock wifi
permit nopass 1000 as root cmd /usr/bin/rfkill args unblock bluetooth

permit nopass 1000 as root cmd /usr/bin/archlinux-java args set java-21-openjdk

permit nopass 1000 as root cmd /usr/bin/mkdir args -p /usr/local/lib
permit nopass 1000 as root cmd /usr/bin/mkdir args -p /etc/pacman.d/hooks
permit nopass 1000 as root cmd /usr/bin/mkdir args --parent /.Trash
permit nopass 1000 as root cmd /usr/bin/mkdir args -p /usr/local/share/applications
EOF

if [ $? -ne 0 ]; then
	echo "Error: No se pudo crear el archivo /etc/doas.conf." >&2
	exit 1
fi

chown root:root /etc/doas.conf
chmod 0600 /etc/doas.conf
mv /etc/sudoers /etc/sudoers.bak

# Desinstalar sudo
echo "Desinstalando sudo..."
if command -v sudo &>/dev/null; then
	pacman -Rcns sudo --noconfirm
fi

# yay necesitará /usr/bin/sudo durante la instalación de doas-sudo-shim-v,
# por lo que, para que yay pueda usar privilegios elevados, crearemos un enlace
# simbólico temporal de OpenDoas en /usr/bin/sudo y permitiremos que yay lo
# sobrescriba con --overwrite="*".
ln -s /usr/bin/doas /usr/bin/sudo

# Instalar doas-sudo-shim-v para que las aplicaciones que dependen
# de sudo puedan seguir funcionando
echo "Instalando doas-sudo-shim..."
if command -v yay &>/dev/null; then
	runuser "$RUSER" -c \
		"yay -S --noconfirm --disable-download-timeout --needed \
		doas-sudo-shim-v --overwrite=\"*\""
else
	echo "Error: yay no está instalado." >&2
	exit 1
fi

# Mensaje final
echo "Configuración completada. Ahora se está utilizando OpenDoas en lugar de sudo."
