font_family Google Sans Code
bold_font auto
italic_font auto
font_size 13.0
window_margin_width 4
text_composition_strategy platform

map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
map ctrl+plus change_font_size all +1
map ctrl+minus change_font_size all -1
map ctrl+shift+plus change_font_size all 0
map ctrl+shift+minus change_font_size all 0
map ctrl+shift+enter launch --cwd=current --type=os-window

background_opacity 1
cursor_shape block
cursor_blink_interval 0.75

enable_audio_bell no
open_url_with xdg-open
confirm_os_window_close 0

remember_window_size no
initial_window_width 800
initial_window_height 600

# (Github Dark Dimmed) Colors for kitty

background #22272e
foreground #adbac7
url_color #adbac7

cursor #adbac7
cursor_text_color background

# Tabs
active_tab_background #57ab5a
active_tab_foreground #22272e
inactive_tab_background #253040
inactive_tab_foreground #636e7b

# Windows Border
active_border_color #539bf5
inactive_border_color #333940

# normal
color0 #545d68
color1 #f47067
color2 #57ab5a
color3 #c69026
color4 #539bf5
color5 #b083f0
color6 #39c5cf
color7 #909dab

# bright
color8 #636e7b
color9 #ff938a
color10 #6bc46d
color11 #daaa3f
color12 #6cb6ff
color13 #dcbdfb
color14 #56d4dd
color15 #cdd9e5

# See https://github.com/be5invis/Iosevka/issues/248
# See https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points
symbol_map U+E5FA-U+E6AC Symbols Nerd Font Mono
symbol_map U+E700-U+E7C5 Symbols Nerd Font Mono
symbol_map U+F000-U+F2E0 Symbols Nerd Font Mono
symbol_map U+E200-U+E2A9 Symbols Nerd Font Mono
symbol_map U+F0001-U+F1AF0 Symbols Nerd Font Mono
symbol_map U+E300-U+E3E3 Symbols Nerd Font Mono
symbol_map U+F400-U+F532,U+2665,U+26A1 Symbols Nerd Font Mono
symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3 Symbols Nerd Font Mono
symbol_map U+E0A3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4 Symbols Nerd Font Mono
symbol_map U+23FB-U+23FE,U+2B58 Symbols Nerd Font Mono
symbol_map U+F300-U+F32F Symbols Nerd Font Mono
symbol_map U+E000-U+E00A Symbols Nerd Font Mono
symbol_map U+EA60-U+EBEB Symbols Nerd Font Mono
symbol_map U+E276C-U+E2771 Symbols Nerd Font Mono # Heavy Angle Brackets
symbol_map U+2500-U+259F Symbols Nerd Font Mono # Box Drawing
symbol_map U+F102,U+F116-U+F118,U+F12F,U+F13E,U+F1AF,U+F1BF,U+F1CF,U+F1FF,U+F20F,U+F21F-U+F220,U+F22E-U+F22F,U+F23F,U+F24F,U+F25F nonicons
symbol_map U+1F600-U+1F64F Noto Color Emoji
