#!/bin/bash
# shellcheck disable=SC1091

# Script para configurar los servicios del sistema y de usuario (systemd)
# - Invocado por /update.sh

source "$HOME/.dotfiles/assets/shell/shell-utils"

[ "$(id -u)" -eq 0 ] && exit 1

# Activar servicio
service_add() {
	SERVICE="$1"
	sudo /usr/bin/systemctl enable --now "$SERVICE" >/dev/null 2>&1 ||
		log "no se pudo inciar el servicio: $SERVICE" WARN
}
# Activar servicio para el usuario
user_service_add() {
	SERVICE="$1"
	systemctl --user enable --now "$SERVICE" >/dev/null 2>&1 ||
		log "no se pudo inciar el servicio: $SERVICE" WARN
}

[ "$(id -u)" -eq 0 ] && exit 1

SERVICES=(
	"NetworkManager"
	"acpid"
	"chronyd"
	"cronie"
	"cups"
	"earlyoom"
	"fwupd"
	"input-remapper"
	"lactd"
	"nix-daemon"
	"power-profiles-daemon"
	"syslog-ng@default.service"
)

USER_SERVICES=(
	"pipewire"
	"pipewire-pulse"
	"syncthing"
	"wireplumber"
)

# Activar los servicios del sistema del runlevel default
for SERVICE in "${SERVICES[@]}"; do
	service_add "$SERVICE" >/dev/null &
done

# Activar los servicios del usuario del runlevel default
for USER_SERVICE in "${USER_SERVICES[@]}"; do
	user_service_add "$USER_SERVICE" &
done
