#!/bin/bash

# Script para configurar los servicios del sistema y de usuario (systemd)
# - Invocado por /update.sh

[ "$(id -u)" -eq 0 ] && exit 1

DEBUG=false

# Comprobamos si el script se ejecutó en modo debug
while getopts "d" opt; do
	case $opt in
	d) DEBUG=true ;;
	*) ;;
	esac
done

# Si está en modo debug, activamos xtrace
if [ "$DEBUG" = true ]; then
	set -x
fi

# Activar servicio
service_add() {
	SERVICE="$1"
	sudo /usr/bin/systemctl enable --now "$SERVICE"
}
# Activar servicio para el usuario
user_service_add() {
	SERVICE="$1"
	systemctl --user enable --now "$SERVICE"
}

[ "$(id -u)" -eq 0 ] && exit 1

SERVICES=(
	"earlyoom"
	"fwupd"
	"gdm"
	"input-remapper"
	"power-profiles-daemon"
	"syslog-ng@default.service"
)

USER_SERVICES=(
	"pipewire"
	"pipewire-pulse"
	"syncthing"
	"wireplumber"
)

# Activar los servicios del sistema del runlevel default
for SERVICE in "${SERVICES[@]}"; do
	service_add "$SERVICE" >/dev/null 2>&1
done

# Activar los servicios del usuario del runlevel default
for USER_SERVICE in "${USER_SERVICES[@]}"; do
	user_service_add "$USER_SERVICE" >/dev/null 2>&1
done
