#!/bin/bash

# Script que crea enlaces simbólicos en /usr/local/bin para ciertos scripts
# - Invocado por /update.sh

[ "$(id -u)" -eq 0 ] && exit 1

FILES=(
	"cleanup-old-modules"
	"rdp-connect"
	"wakeat"
	"wakeme"
)
for FILE in "${FILES[@]}"; do
	[ -e "/usr/local/bin/$FILE" ] && sudo /usr/bin/rm /usr/local/bin/"$FILE"
	sudo /usr/bin/install -o root -g root -m 0755 \
		"$HOME/.dotfiles/assets/bin/$FILE" "/usr/local/bin/$FILE"
done
