#!/bin/bash

# Script para recompilar las aplicaciones suckless
# - Invocado por /update.sh

[ "$(id -u)" -eq 0 ] && exit 1

########
# UDEV #
########

# Permitir a Steam controlar mandos de PlayStation 4
sudo /usr/bin/cp -f "$HOME/.dotfiles/assets/system/udev/99-steam-controller-perms.rules" \
	/usr/lib/udev/rules.d/

# Permitir al usuario escanear redes Wi-Fi y cambiar ajustes de red
id -nG "$USER" | grep network -q || sudo /usr/bin/usermod -aG network "$USER"

if [ -e /sys/class/power_supply/BAT0 ]; then
	sudo /usr/bin/cp -f \
		"$HOME/.dotfiles/assets/system/udev/50-org.freedesktop.NetworkManager.rules" \
		/etc/polkit-1/rules.d/
fi

################
# Aplicaciones #
################

# Configurar keepassxc para que siga el tema de QT (Si no está ya configurado)
if [ ! -f "$HOME/.config/keepassxc/keepassxc.ini" ]; then
	mkdir -p "$HOME/.config/keepassxc"
	cp "$HOME/.dotfiles/assets/configs/apps/keepassxc/keepassxc.ini" \
		"$HOME"/.config/keepassxc/
fi

##############
# Miscelánea #
##############

# Desactivar el altavoz del PC
echo "blacklist pcspkr" | sudo /usr/bin/tee /etc/modprobe.d/nobeep.conf >/dev/null

# Suspender de forma automática cuando la batería cae por debajo del 10%
if [ -e /sys/class/power_supply/BAT0 ]; then
	if [ ! -e /usr/local/bin/auto-suspend ]; then
		sudo /usr/bin/cp \
			"$HOME/.dotfiles/assets/system/services/auto-suspend/auto-suspend" \
			/usr/local/bin/auto-suspend
		sudo /usr/bin/chmod 755 /usr/local/bin/auto-suspend
	fi

	if [ ! -e /usr/local/bin/auto-suspend-loop ]; then
		sudo /usr/bin/cp \
			"$HOME/.dotfiles/assets/system/services/auto-suspend/auto-suspend-loop" \
			/usr/local/bin/auto-suspend-loop
		sudo chmod 755 /usr/local/bin/auto-suspend-loop
	fi

	if [ ! -e /etc/systemd/system/auto-suspend.service ]; then
		sudo /usr/bin/cp
		"$HOME/.dotfiles/assets/system/services/auto-suspend/systemd-service" \
			/etc/systemd/system/auto-suspend.service
		sudo chmod /etc/systemd/system/auto-suspend.service 644
	fi

	sudo /usr/bin/systemctl enable auto-suspend
fi
