#!/bin/bash

# Script que crea enlaces simbólicos en /usr/local/bin para ciertos scripts
# - Invocado por /update.sh

[ "$(id -u)" -eq 0 ] && exit 1

FILES=(
	"cleanup-old-modules"
	"rdp-connect"
	"wakeat"
	"wakeme"
)
for FILE in "${FILES[@]}"; do
	sudo ln -sf "$HOME/.dotfiles/assets/bin/$FILE" "/usr/local/bin/$FILE"
done
