#!/bin/bash

# Script para configurar diversas partes del sistema
# - Invocado por /update.sh

[ "$(id -u)" -eq 0 ] && exit 1

DEBUG=false

# Comprobamos si el script se ejecutó en modo debug
while getopts "d" opt; do
	case $opt in
	d) DEBUG=true ;;
	*) ;;
	esac
done

# Si está en modo debug, activamos xtrace
if [ "$DEBUG" = true ]; then
	set -x
fi

########
# UDEV #
########

# Permitir a Steam controlar mandos de PlayStation 4
sudo /usr/bin/cp -f "$HOME/.dotfiles/assets/system/udev/99-steam-controller-perms.rules" \
	/usr/lib/udev/rules.d/

################
# Aplicaciones #
################

# Configurar keepassxc para que siga el tema de QT (Si no está ya configurado)
if [ ! -f "$HOME/.config/keepassxc/keepassxc.ini" ]; then
	mkdir -p "$HOME/.config/keepassxc"
	cp "$HOME/.dotfiles/assets/configs/apps/keepassxc/keepassxc.ini" \
		"$HOME"/.config/keepassxc/
fi

# Configurar el inverse search de vimtex para okular
if [ ! -e "$HOME"/.config/okularpartrc ] ||
	! grep -q okular-inverse-search "$HOME"/.config/okularpartrc; then
	cat <<-EOF >~/.config/okularpartrc
		[Core General]
		ExternalEditor=Custom
		ExternalEditorCommand=okular-inverse-search %l "%f"
	EOF
fi

##############
# Miscelánea #
##############

# Desactivar el altavoz del PC
echo "blacklist pcspkr" | sudo /usr/bin/tee /etc/modprobe.d/nobeep.conf >/dev/null

# No suspender el portátil al cerrar la tapa
# si está enchufado o conectado a un monitor
if ! grep -q "^HandleLidSwitchExternalPower=ignore" /etc/systemd/logind.conf; then
	sudo /usr/bin/sed -i '/^#\?HandleLidSwitchExternalPower=/c\HandleLidSwitchExternalPower=ignore' /etc/systemd/logind.conf
	sudo /usr/bin/sed -i '/^#\?HandleLidSwitchDocked=/c\HandleLidSwitchDocked=ignore' /etc/systemd/logind.conf
	sudo /usr/bin/sed -i '/^#\?LidSwitchIgnoreInhibited=/c\LidSwitchIgnoreInhibited=yes' /etc/systemd/logind.conf
fi

# Si el dispositivo tiene una batería activar el servicio de auto-suspensión
if [ -e /sys/class/power_supply/BAT0 ]; then
	sudo /usr/bin/systemctl enable auto-suspend
# Si no la tiene, desactivarlo
else
	sudo /usr/bin/systemctl disable auto-suspend
fi
