#!/bin/bash

# Script para configurar diversas partes del sistema
# - Invocado por /update.sh

source "$HOME/.dotfiles/assets/shell/shell-utils"

[ "$(id -u)" -eq 0 ] && exit 1

# UDEV
#-------------------------------------------------------------------------------

# Permitir a Steam controlar mandos de PlayStation 4
sudo /usr/bin/cp -f "$HOME/.dotfiles/assets/system/udev/99-steam-controller-perms.rules" \
	/usr/lib/udev/rules.d/

# Aplicaciones
#-------------------------------------------------------------------------------

# Configurar keepassxc para que siga el tema de QT (Si no está ya configurado)
if [ ! -f "$HOME/.config/keepassxc/keepassxc.ini" ]; then
	mkdir -p "$HOME/.config/keepassxc"
	cp "$HOME/.dotfiles/assets/configs/apps/keepassxc/keepassxc.ini" \
		"$HOME"/.config/keepassxc/
fi

# Configurar Okular
cat <<-EOF >~/.config/okularpartrc
	[Core General]
	ExternalEditor=Custom
	ExternalEditorCommand=okular-inverse-search %l "%f"

	[Dlg Accessibility]
	RecolorBackground=40,40,40
	RecolorForeground=251,241,199

	[Document]
	ChangeColors=true
	RenderMode=Recolor

	[Main View]
	ShowBottomBar=true

	[PageView]
	BackgroundColor=29,32,33
	MouseMode=TextSelect
	UseCustomBackgroundColor=true
EOF
cat <<-EOF >~/.config/okularrc
	[Desktop Entry]
	FullScreen=false

	[General]
	LockSidebar=true
	ShowSidebar=true

	[UiSettings]
	ColorScheme=KritaDarkOrange
EOF

# REAPER
#-------------------------------------------------------------------------------

# Fix for: https://github.com/Supreeeme/xwayland-satellite/issues/306

REAPER_LOCAL_DESKTOP="$HOME/.local/share/applications/cockos-reaper.desktop"
REAPER_DESKTOP="/usr/share/applications/cockos-reaper.desktop"
REAPER_WRAPPER="$HOME/.local/bin/utils/reaper-xephyr"

if [ -x /usr/bin/reaper ]; then
	ensure_dir "$(dirname "$REAPER_LOCAL_DESKTOP")"
	rm -f "$REAPER_LOCAL_DESKTOP"
	cp "$REAPER_DESKTOP" "$REAPER_LOCAL_DESKTOP"
	sed -i "s|/usr/lib/REAPER/reaper|$REAPER_WRAPPER|" "$REAPER_LOCAL_DESKTOP"
else
	rm -f "$REAPER_LOCAL_DESKTOP"
fi

#-------------------------------------------------------------------------------

# Desactivar el altavoz del PC
echo "blacklist pcspkr" | sudo /usr/bin/tee /etc/modprobe.d/nobeep.conf >/dev/null

# No suspender el portátil al cerrar la tapa
# si está enchufado o conectado a un monitor
if ! grep -q "^HandleLidSwitchExternalPower=ignore" /etc/systemd/logind.conf; then
	sudo /usr/bin/sed -i '/^#\?HandleLidSwitchExternalPower=/c\HandleLidSwitchExternalPower=ignore' /etc/systemd/logind.conf
	sudo /usr/bin/sed -i '/^#\?HandleLidSwitchDocked=/c\HandleLidSwitchDocked=ignore' /etc/systemd/logind.conf
	sudo /usr/bin/sed -i '/^#\?LidSwitchIgnoreInhibited=/c\LidSwitchIgnoreInhibited=yes' /etc/systemd/logind.conf
fi

if [ -e /sys/class/power_supply/BAT0 ]; then
	sudo /usr/bin/systemctl enable auto-suspend
else
	sudo /usr/bin/systemctl disable auto-suspend
fi
