#!/bin/bash
# shellcheck disable=SC2046

source "$HOME/.dotfiles/assets/shell/shell-utils"

[ "$(id -u)" -eq 0 ] && exit 1

gcc -o "$TMP_DIR"/file-handler ~/.dotfiles/assets/file-handler.c \
	$(pkg-config --cflags --libs dbus-1)

install -m 755 "$TMP_DIR"/file-handler "$HOME/.local/bin/file-handler"
