#!/bin/bash
# shellcheck disable=SC1091

# Script para instalar paquetes de nixpkgs
# - Invocado por /update.sh

source "$HOME/.dotfiles/assets/shell/shell-utils"

[ "$(id -u)" -eq 0 ] && exit 1
check_connection || exit 1

export NIXPKGS_ALLOW_UNFREE=1
export NIXPKGS_ALLOW_INSECURE=1

init_log nixpkgs >/dev/null

LATEST_VERSION=$(
	curl -s https://api.github.com/repos/NixOS/nixpkgs/tags |
		jq -r '.[].name' | grep -oP "[0-9]{2}\.[0-9]{2}$" | sort -run | head -n1
)

#-------------------------------------------------------------------------------

CHANNELS=(
	"https://nixos.org/channels/nixpkgs-unstable"
)

for CHANNEL in "${CHANNELS[@]}"; do
	nix-channel --add "$CHANNEL" >/dev/null 2>&1
done
nix-channel --update >/dev/null 2>&1

#-------------------------------------------------------------------------------

nix profile wipe-history >/dev/null 2>&1
nix-env --delete-generations old >/dev/null 2>&1
nix-collect-garbage -d >/dev/null 2>&1

#-------------------------------------------------------------------------------

PACKAGES_DIR="$HOME/.dotfiles/assets/packages"

mapfile -t TARGET_PACKAGES < <(jq -c '.[] | .[] | select(has("name"))' <(remove_comments "$PACKAGES_DIR/nix.json"))

[ -f "$PACKAGES_DIR/nix_local.json" ] && {
	mapfile -t TARGET_LOCAL_PACKAGES < <(jq -c '.[] | .[] | select(has("name"))' <(remove_comments "$PACKAGES_DIR/nix_local.json"))
	TARGET_PACKAGES+=("${TARGET_LOCAL_PACKAGES[@]}")
}

# Obtener paquetes instalados y sus versiones
declare -A INSTALLED_MAP
while IFS= read -r line; do
	NAME=$(echo "$line" | jq -r '.value.attrPath' | grep -oP 'linux\.\K.*')
	ORIGINAL_URL=$(echo "$line" | jq -r '.value.originalUrl // empty')
	VERSION=$(echo "$ORIGINAL_URL" | grep -oP "nixpkgs/\K.*")
	INSTALLED_MAP["$NAME"]="$VERSION"
done < <(nix profile list --json | jq -c '.elements | to_entries[]')

declare -A TARGET_MAP
for pkg in "${TARGET_PACKAGES[@]}"; do
	NAME=$(echo "$pkg" | jq -r '.name')
	TARGET_MAP["$NAME"]=1
done

for pkg in "${!INSTALLED_MAP[@]}"; do
	if [ -z "${TARGET_MAP[$pkg]:-}" ]; then
		log "borrando $pkg" WARN
		nix profile remove "$pkg" >/dev/null 2>&1
	fi
done

# Instalar o actualizar
for pkg in "${TARGET_PACKAGES[@]}"; do
	NAME=$(echo "$pkg" | jq -r '.name')
	TARGET_VERSION=$(echo "$pkg" | jq -r '.version // empty')
	[ -z "$TARGET_VERSION" ] && TARGET_VERSION="$LATEST_VERSION"

	if [[ -n "$TARGET_VERSION" ]]; then
		# usar flake con commit si se especifica versión
		FLAKE_REF="github:NixOS/nixpkgs/$TARGET_VERSION#$NAME"
	else
		FLAKE_REF="nixpkgs#$NAME"
	fi

	INSTALLED_VERSION="${INSTALLED_MAP[$NAME]:-}"

	if [[ -z "$INSTALLED_VERSION" ]]; then
		nix profile add --impure "$FLAKE_REF" >/dev/null
	elif [[ "$INSTALLED_VERSION" != "$TARGET_VERSION" ]]; then
		log "cambiando versión $NAME: $INSTALLED_VERSION -> $TARGET_VERSION" WARN
		nix profile remove "${NAME##*.}" >/dev/null 2>&1
		nix profile add --impure "$FLAKE_REF"
	fi
done
