#!/bin/sh
# shellcheck disable=SC1091,SC2164

export REPO_DIR="$HOME/.dotfiles"

# Abreviaciones
if [ -e "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/aliasrc" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/aliasrc"
fi

# Aquí puedes colocar alias sin que estos esten
# dentro de la estructura del repositorio
if [ -e "${XDG_CONFIG_HOME:-$HOME/.config}/useralias" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/useralias"
fi

[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin:$PATH"
[ -d "$HOME/.local/bin/utils" ] && PATH="$HOME/.local/bin/utils:$PATH"
[ -d "$HOME/.local/bin/installers/" ] && PATH="$HOME/.local/bin/installers:$PATH"
[ -d "$HOME/.nix-profile/bin" ] && PATH="$HOME/.nix-profile/bin:$PATH"

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export OPENER="xdg-open"

export GDK_SCALE=1
export GTK_USE_PORTAL=1

# Hacer que las aplicaciones QT sigan los ajustes de QT5CT
export QT_QPA_PLATFORMTHEME="qt6ct"

export XCURSOR_PATH="/usr/share/icons:${XDG_DATA_HOME}/icons"
export XCURSOR_THEME=capitaine-cursors
export XCURSOR_SIZE=64

export EDITOR="nvim"
export SUDO_EDITOR="nvim"
export READER="okular"
export TERMINAL="kitty --single-instance"
export SCRATCH_OPTS="--instance-group=scratchpad"
export REGULAR_OPTS="--instance-group=kitty"
export TERMTITLE="-T"
export TERMEXEC=""
export BROWSER="firefox"
export VIDEO="vlc"
export PAGER="less"
export VIEWER="nsxiv"

export _JAVA_AWT_WM_NONREPARENTING=1

# Limpiar el directorio ~/ de archivos de configuración
alias wget='wget --hsts-file="$XDG_CONFIG_HOME"/wget-hsts'
alias gpg2='gpg2 --homedir "$XDG_DATA_HOME"/gnupg'
export PARALLEL_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"/parallel
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export GOPATH="$XDG_DATA_HOME"/go
export TEXMFVAR="$XDG_CACHE_HOME"/texlive/texmf-var
export KODI_DATA="$XDG_DATA_HOME"/kodi
export DVDCSS_CACHE="$XDG_DATA_HOME"/dvdcss
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export CUDA_CACHE_PATH="${XDG_CACHE_HOME:-$HOME/.cache}/nv"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc:${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkfilechooser.ini"
export WINEPREFIX="${XDG_CONFIG_HOME:-$HOME/.config}/wineprefixes"
export TERMINFO_DIRS="${XDG_CONFIG_HOME:-$HOME/.config}/terminfo:/usr/share/terminfo"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"/npm/npmrc

check_connection() {
	curl -s --connect-timeout 3 https://dns.google/ >/dev/null
}

if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
	# En el primer arranque real del sistema se ejecutará update.sh de nuevo
	# para completar las tareas que no pueden realizarse dentro del chroot
	[ -f "$HOME/.system_not_initialized" ] && check_connection && (
		cd "$REPO_DIR"
		./update.sh &
		~/.dotfiles/installer/post_install/tauon-config
		~/.dotfiles/installer/post_install/firefox-config
		nvim --headless +qa >/dev/null 2>&1
		wait
		rm "$HOME/.system_not_initialized"
	)
	exec start-hyprland
fi
