#!/bin/bash
# shellcheck disable=SC1091

source "$HOME/.dotfiles/assets/shell/shell-utils-sh"

if [ "$DEBUG" = true ]; then
	export PS4='+ $(date "+%H:%M:%S"): '
	set -xEeo pipefail
fi

# Utilidad para facilitar el depurado de los scripts
# Todos los scripts que importen el archivo deberán usar bash para poder
# hacer uso de variables como $BASH_COMMAND

error_trap() {
	local exit_code=$?
	log "{$exit_code} en línea $1: $2" ERROR
}

trap 'error_trap $LINENO "$BASH_COMMAND"' ERR
