#!/bin/bash
# shellcheck disable=SC2155

if [ "$DEBUG" = true ]; then
	export PS4='+ $(date "+%H:%M:%S"): '
	set -xEeuo pipefail
fi

export LOG_BASE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles"
export TMP_BASE_DIR="/tmp/00_dotfiles"

ensure_dir() {
	[ ! -d "$1" ] && mkdir -p "$1"
	echo "$1"
}

# Utilidad para facilitar el depurado de los scripts
# Todos los scripts que importen el archivo deberán usar bash para poder
# hacer uso de variables como $BASH_COMMAND

error_trap() {
	local exit_code=$?
	log "{$exit_code} en línea $1: $2" ERROR
}

trap 'error_trap $LINENO "$BASH_COMMAND"' ERR

# Utilidades para guardar los logs en un solo directorio
#
# Podemos guardar los logs en un directorio relativo al base usando:
#     initlog <directorio>
#       => logs guardados en $LOG_BASE_DIR/<directorio>
#
# o para que la actualización de la variable LOG_DIR sea más explícita:
#     LOG_DIR=$(initlog <directorio>)

log() {
	local msg="$1"
	local level="${2:-ERROR}"
	local date="$(date '+%Y-%m-%d %H:%M:%S')"
	local module="$(basename "$0")"
	ensure_dir "${LOG_DIR:-$LOG_BASE_DIR}" >/dev/null
	echo -n "$date [$level] ($module) $msg" |
		tee -a "${LOG_DIR:-$LOG_BASE_DIR}/errors.log"
	echo # tee no respeta los saltos de linea
}

init_log() {
	LOG_DIR="$LOG_BASE_DIR/$1"
	ensure_dir "$LOG_DIR"
}

# Utilidades para guardar los archivos temporales en un solo directorio

get_tmp() {
	ensure_dir "$TMP_BASE_DIR/$1"
}

get_random_tmp() {
	ensure_dir "$TMP_BASE_DIR" >/dev/null
	mktemp -d -p "$TMP_BASE_DIR" XXXXXX
}

#-------------------------------------------------------------------------------

download() {
	local url="$1"
	local file="$2"
	if [ ! -f "$file" ]; then
		ensure_dir "$(dirname "$file")"
		curl "$url" -o "$file" 2>/dev/null
		return
	fi

	#log "file already exists: $file" WARN
}

is_chroot() {
	sudo /usr/bin/systemd-detect-virt --chroot >/dev/null 2>&1
}
