#!/bin/bash

# Primero comprobamos la extensión de todos los archivos en $@, agrupamos por
# tipo de archivo y llamamos a ~/.config/lf/opener para cada grupo de archivos
# del mismo tipo.

declare -A FILETYPE_FILES

TEXT_FILES=()
AUDIO_FILES=()

for file in "$@"; do
	FILETYPE="$(file -b --mime-type "$(readlink -f "$file")")"

	#------------------#
	# Aplicaciones TUI #
	#------------------#

	# Las aplicaciones de terminal no pueden abrirse de forma paralela con el
	# opener porque tienen que estar conectadas a la terminal. Debemos añadir
	# excepciones para estas y abrirlas en primer plano desde este script.

	case "$FILETYPE" in
	text/* | */xml | */json | inode/x-empty | */x-shellscript | */x-desktop | */yaml | */sql | */x-php | */x-xbel | \
		image/x-cursor) # xdg-mime/file detectan los archivos Xresources como x-xcursor
		TEXT_FILES+=("$file")
		continue
		;;

	audio/*)
		AUDIO_FILES+=("$file")
		continue
		;;

	#------------------#
	# Aplicaciones GUI #
	#------------------#

	# Queremos que determinados tipos de archivos se agrupen

	video/*) FILETYPE=video ;;

	# Todas las imágenes que no sean x-eps deberán ir juntas
	image/x-eps) FILETYPE=x-eps ;;
	image/*) FILETYPE=image ;;
	esac

	# Añadimos los archivos al mapa separados por |
	if ! [[ -v FILETYPE_FILES["$FILETYPE"] ]]; then
		FILETYPE_FILES["$FILETYPE"]="$file"
	else
		FILETYPE_FILES["$FILETYPE"]+="|$file"
	fi
done

for file_list in "${FILETYPE_FILES[@]}"; do
	IFS='|' read -r -a files_array <<<"$file_list"
	~/.config/lf/opener "${files_array[@]}" &>/dev/null
done

# Aplicaciones de terminal
#-------------------------------------------------------------------------------

mpv --audio-display=no "${AUDIO_FILES[@]}"

for text_file in "${TEXT_FILES[@]}"; do
	$EDITOR "$text_file"
done
