#!/bin/bash
# shellcheck disable=SC1091

# Visualizador de archivos para LF.

source "$HOME/.dotfiles/assets/shell/shell-utils-sh"

LF_CACHE_DIR="$(ensure_dir "${XDG_CACHE_HOME:-$HOME/.cache}/lf")"

W="$2"
H="$3"
Y="$5"
X="$4"

linebreaks() {
	local PREVIEW="$1"
	HEIGHT=$(mediainfo "$PREVIEW" | grep -oP "Height[ ]*: \K.[0-9 ]*" | tr -d ' ')
	WIDTH=$(mediainfo "$PREVIEW" | grep -oP "Width[ ]*: \K.[0-9 ]*" | tr -d ' ')
	RATIO=$(echo "scale=3; $WIDTH / $HEIGHT " | bc)
	COUNT=$(echo "(${X}/4) / $RATIO + 2" | bc)
	printf '\n%.0s' $(seq "$COUNT")
}

display() {
	if [ -f "$1" ] && [ -n "$WAYLAND_DISPLAY" ] && [ -z "$SSH_CONNECTION" ]; then
		kitten icat --stdin no --transfer-mode memory --place "${W}x${H}@${X}x${Y}" "$1" </dev/null >/dev/tty
		return 0
	else
		return 1
	fi
}

# Función para extraer el hash de un archivo
file_hash() {
	stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" |
		sha256sum | awk '{print $1}'
}

# Función para la preview de archivos que se pueden convertir con imagemagick directamente
magick_convert() {
	CACHE="$LF_CACHE_DIR/thumb.$HASH"
	[ ! -f "$CACHE.jpg" ] && magick "$1" "$CACHE.jpg" >/dev/null 2>&1
	display "$CACHE.jpg"
}

thumbnail_resize() {
	[ -z "$WAYLAND_DISPLAY" ] || [ -n "$SSH_CONNECTION" ] && return
	THUMBNAIL="$1"
	# Ancho mínimo: 1/3 del ancho de pantalla
	THIRD="$(($(hyprctl monitors -j | jq '.[] | select(.focused == true)' | jq -r '.width') / 3))"
	WIDTH=$(identify -format "%w" "$THUMBNAIL")
	# Si el ancho es menor al requerido, lo reescalamos proporcionalmente
	if [ "$WIDTH" -lt "$THIRD" ]; then
		TMP="$(mktemp /tmp/lf.XXXXXX.jpg)"
		convert "$THUMBNAIL" -resize "${THIRD}x" "$TMP"
		mv -f "$TMP" "$THUMBNAIL"
	fi
}

FILETYPE="$(xdg-mime query filetype "$1")"
HASH="$(file_hash "$1")"

case $FILETYPE in

text/troff) man ./ "$1" | col -b ;;

text/plain)
	# Para archivos de texto plano nos fijamos en la extensión
	case "${1##*.}" in
	hjson) bat -fp -l JSON <<<"$(hjson -j "$1")" ;;
	# Extensión desconocida: mostrar como texto plano
	*) bat -fp --terminal-width "$((4 - 2))" -f "$1" ;;
	esac
	;;

text/* | */xml | */x-shellscript | */x-xcursor | */x-theme | */x-desktop | */x-troff-man | */x-ruby | */yaml | */toml | */sql | */x-php | */x-empty | */x-xbel)
	# Comprobar si es un archivo de texto
	case "$(file --dereference --brief --mime-type -- "$1")" in
	*/pgp-keys) gpg --list-packets "$1" ;;
	*/*) bat -fp --terminal-width "$((4 - 2))" -f "$1" ;;
	esac
	;;

# Convertir a .png
image/svg+xml*)
	CACHE_FILE="$LF_CACHE_DIR/$HASH.png"
	[ ! -f "$CACHE_FILE" ] &&
		DISPLAY="" inkscape -o "$CACHE_FILE" --export-overwrite -D --export-width=256 "$1"
	display "$CACHE_FILE"
	;;

# Convertir a JPG
image/x-eps)
	CACHE_FILE="$LF_CACHE_DIR/$HASH.jpg"
	[ ! -f "$CACHE_FILE" ] && gs -dSAFER -dBATCH -dNOPAUSE -sDEVICE=jpeg -r300 -dEPSCrop -sOutputFile="$CACHE_FILE" "$1" >/dev/null 2>&1
	display "$CACHE_FILE"
	;;

# Mostrar la carátula y metadatos
audio/flac | audio/mpeg | audio/x-m4a | audio/mp4)
	CACHE_DIR="$LF_CACHE_DIR/$HASH"
	METADATA="$CACHE_DIR/metadata.txt"
	COVER="$CACHE_DIR/cover.jpg"

	ensure_dir "$CACHE_DIR" >/dev/null
	[ ! -f "$COVER" ] && ffmpeg -nostdin -i "$1" "$COVER" && thumbnail_resize "$COVER"
	[ ! -f "$METADATA" ] && {
		TMP="$(mktemp /tmp/lf.XXXX)"
		ffmpeg -i "$1" -y -f ffmetadata "$TMP"
		[ "$FILETYPE" = "audio/flac" ] &&
			mediainfo --Inform="Audio;%BitDepth% bit / %SamplingRate% Hz" "$1" >"$METADATA"
		grep -ivE "(comment|encoder|ffmetadata1)" "$TMP" >>"$METADATA"
		rm "$TMP"
	}

	display "$COVER" && linebreaks "$COVER"
	cat "$METADATA"
	;;

*/x-iso9660-image | */vnd.efi.iso)
	CACHE_FILE="$LF_CACHE_DIR/$HASH.txt"
	[ ! -f "$CACHE_FILE" ] && {
		isoinfo -d -i "$1" |
			grep "Volume id\|Publisher\|Data preparer\|Application" |
			tee "$CACHE_FILE" >/dev/null
	}

	cat "$CACHE_FILE"
	;;

video/*)
	CACHE_DIR="$LF_CACHE_DIR/$HASH"
	THUMBNAIL="$CACHE_DIR/thumbnail.jpg"
	METADATA="$CACHE_DIR/metadata.txt"
	ensure_dir "$CACHE_DIR" >/dev/null
	[ ! -f "$THUMBNAIL" ] && ffmpegthumbnailer -i "$1" -o "$THUMBNAIL" -s 0 && thumbnail_resize "$THUMBNAIL"
	[ ! -f "$METADATA" ] && {
		TMP="$(mktemp /tmp/lf.XXXX)"
		mediainfo "$1" | tr '\t' ' ' | tr -s " " | tee "$TMP" >/dev/null
		for FIELD in "File size" "Duration" "Frame rate" "Format" "Width" "Height" "Bit depth"; do
			grep "^$FIELD" "$TMP" | head -n1 >>"$METADATA"
		done
		grep "^Language" "$TMP" | sort -u >>"$METADATA"
		rm "$TMP"
	}

	display "$THUMBNAIL" && linebreaks "$THUMBNAIL"
	cat "$METADATA"
	;;

*/pdf)
	CACHE_FILE="$LF_CACHE_DIR/$HASH.jpg"
	# Usando -dUseCropBox usamos la parte visible de la página en vez de
	# mantener el tamaño de página definido en el PDF
	[ ! -f "$CACHE_FILE" ] &&
		gs -sDEVICE=jpeg -dUseCropBox -dFirstPage=1 -dLastPage=1 -r300 -o "$CACHE_FILE" "$1" >/dev/null

	display "$CACHE_FILE"
	;;

# Mostar la primera página del comic
*/vnd.comicbook+zip | */vnd.comicbook-rar | */epub+zip)
	CACHE_FILE="$LF_CACHE_DIR/$HASH"
	FIRST_IMAGE=$(7z l "$1" | grep "jpg\|png" | awk '{print substr($0, index($0,$6))}' | sort | head -n1)
	EXTENSION=${FIRST_IMAGE//*./}
	CACHE_FILE+=".${EXTENSION}"
	[ ! -f "$CACHE_FILE" ] && {
		[ -z "$FIRST_IMAGE" ] && exit
		TMP_DIR="$(get_tmp_dir lf)"

		7z e "$1" "$FIRST_IMAGE" -o"$TMP_DIR" >/dev/null 2>&1
		mv "$TMP_DIR/$(basename "$FIRST_IMAGE")" "$CACHE_FILE"
		rm -rf "$TMP_DIR"
	}

	display "$CACHE_FILE"
	;;

# Listar archivos y ver preview
*/x-krita)
	CACHE_DIR="$LF_CACHE_DIR/$HASH"
	PREVIEW="$CACHE_DIR/preview.png"
	FILE_LIST="$CACHE_DIR/filelist.txt"
	ensure_dir "$CACHE_DIR"
	[ ! -f "$FILE_LIST" ] && unzip -l "$1" | tee "$FILE_LIST" >/dev/null
	[ ! -f "$PREVIEW" ] && {
		7z e "$1" preview.png -o"$CACHE_DIR" >/dev/null 2>&1 &&
			thumbnail_resize "$PREVIEW"
	}

	display "$PREVIEW" && linebreaks "$PREVIEW"
	cat "$FILE_LIST"
	;;

*/json*) bat -fp --terminal-width "$((4 - 2))" -l JSON "$1" ;;
*/pgp-encrypted) gpg --list-packets "$1" ;;
*/postscript | */x-xpixmap | */x-xcf | */heif | */bmp) magick_convert "$1" ;;
*/vnd.rar | */zip | */vnd.android.package-archive | */x-7z-compressed) 7z l "$1" ;;
*/x-tar | */x-compressed-tar) tar -tf "$1" ;;
*opendocument*) odt2txt "$1" ;;
image/*) display "$1" ;;
*) mediainfo "$1" | tr -s " " ;;

esac

exit 1
