#!/bin/bash

# Visualizador de archivos para LF.

mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/lf"

W="$2"
H="$3"
Y="$5"
X="$4"

linebreaks() {
	local PREVIEW="$1"
	HEIGHT=$(mediainfo "$PREVIEW" | grep -oP "Height[ ]*: \K.[0-9 ]*" | tr -d ' ')
	WIDTH=$(mediainfo "$PREVIEW" | grep -oP "Width[ ]*: \K.[0-9 ]*" | tr -d ' ')
	RATIO=$(echo "scale=3; $WIDTH / $HEIGHT " | bc)
	COUNT=$(echo "(${X}/4) / $RATIO + 1" | bc)
	printf '\n%.0s' $(seq "$COUNT")
}

draw() {
	if [ -f "$1" ] && [ -n "$WAYLAND_DISPLAY" ] && [ -z "$SSH_CONNECTION" ]; then
		kitten icat --stdin no --transfer-mode memory --place "${W}x${H}@${X}x${Y}" "$1" </dev/null >/dev/tty
		return 0
	else
		return 1
	fi
}

# Función para extraer el hash de un archivo
file_hash() {
	stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" |
		sha256sum | awk '{print $1}'
}

# Función para la preview de archivos que se pueden convertir con imagemagick directamente
magick_convert() {
	CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$HASH"
	[ ! -f "$CACHE.jpg" ] && magick "$1" "$CACHE.jpg" >/dev/null 2>&1
	draw "$CACHE.jpg"
}

thumbnail_resize() {
	[ -z "$WAYLAND_DISPLAY" ] || [ -n "$SSH_CONNECTION" ] && return
	THUMBNAIL="$1"
	# Ancho mínimo: 1/3 del ancho de pantalla
	THIRD="$(($(hyprctl monitors -j | jq '.[] | select(.focused == true)' | jq -r '.width') / 3))"
	WIDTH=$(identify -format "%w" "$THUMBNAIL")
	# Si el ancho es menor al requerido, lo reescalamos proporcionalmente
	if [ "$WIDTH" -lt "$THIRD" ]; then
		TMP="$(mktemp /tmp/lf.XXXXXX.jpg)"
		convert "$THUMBNAIL" -resize "${THIRD}x" "$TMP"
		mv -f "$TMP" "$THUMBNAIL"
	fi
}

FILETYPE="$(xdg-mime query filetype "$1")"
HASH="$(file_hash "$1")"

case $FILETYPE in

text/troff) man ./ "$1" | col -b ;;

text/* | */xml | */x-shellscript | */x-xcursor | */x-theme | */x-desktop | */x-troff-man | */x-ruby | */yaml | */toml | */sql | */x-php | inode/x-empty)
	# Comprobar si es un archivo de texto
	case "$(file --dereference --brief --mime-type -- "$1")" in
	application/pgp-keys) gpg --list-packets "$1" ;;
	*/*) bat -fp --terminal-width "$((4 - 2))" -f "$1" ;;
	esac
	;;

# Convertir a .png
image/svg+xml*)
	CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$HASH"
	[ ! -f "$CACHE.png" ] && DISPLAY="" inkscape -o "$CACHE.png" --export-overwrite -D --export-width=256 "$1"
	draw "$CACHE.png"
	;;

# Convertir a JPG
image/x-eps)
	CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$HASH"
	[ ! -f "$CACHE.jpg" ] && gs -dSAFER -dBATCH -dNOPAUSE -sDEVICE=jpeg -r300 -dEPSCrop -sOutputFile="$CACHE.jpg" "$1" >/dev/null 2>&1
	draw "$CACHE.jpg"
	;;

# Mostrar la carátula y metadatos
audio/flac | audio/mpeg | audio/x-m4a | audio/mp4)
	CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/lf/$HASH"
	METADATA="$CACHE_DIR/metadata.txt"
	COVER="$CACHE_DIR/cover.jpg"

	[ ! -d "$CACHE_DIR" ] && mkdir -p "$CACHE_DIR"
	[ ! -f "$COVER" ] && ffmpeg -nostdin -i "$1" "$COVER" && thumbnail_resize "$COVER"
	[ ! -f "$METADATA" ] && {
		TMP="$(mktemp /tmp/lf.XXXX)"
		ffmpeg -i "$1" -y -f ffmetadata "$TMP"
		[ "$FILETYPE" = "audio/flac" ] &&
			mediainfo --Inform="Audio;%BitDepth% bit / %SamplingRate% Hz" "$1" >"$METADATA"
		grep -ivE "(comment|encoder|ffmetadata1)" "$TMP" >>"$METADATA"
		rm "$TMP"
	}

	draw "$COVER" && linebreaks "$COVER"
	cat "$METADATA"
	;;

*/x-iso9660-image | */vnd.efi.iso)
	CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/$HASH.txt"
	[ ! -f "$CACHE" ] && {
		isoinfo -d -i "$1" |
			grep "Volume\|Publisher\|Data preparer\|Application" |
			tee "$CACHE" >/dev/null
	}

	[ -z "$SSH_CONNECTION" ] &&
		chafa /usr/share/icons/Papirus-Dark/128x128/devices/media-optical.svg
	cat "$CACHE"
	;;

video/*)
	CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/lf/$HASH"
	THUMB="$CACHE_DIR/thumb.jpg"
	METADATA="$CACHE_DIR/metadata.txt"
	[ ! -d "$CACHE_DIR" ] && mkdir -p "$CACHE_DIR"
	[ ! -f "$THUMB" ] && ffmpegthumbnailer -i "$1" -o "$THUMB" -s 0 && thumbnail_resize "$THUMB"
	[ ! -f "$METADATA" ] && {
		TMP="$(mktemp /tmp/lf.XXXX)"
		mediainfo "$1" | tr '\t' ' ' | tr -s " " | tee "$TMP" >/dev/null
		for FIELD in "File size" "Duration" "Frame rate" "Format" "Width" "Height" "Bit depth"; do
			grep "^$FIELD" "$TMP" | head -n1 >>"$METADATA"
		done
		grep "^Language" "$TMP" | sort -u >>"$METADATA"
		rm "$TMP"
	}

	draw "$THUMB" && linebreaks "$THUMB"
	cat "$METADATA"
	;;

*/pdf)
	CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$HASH"
	# Usando -dUseCropBox usamos la parte visible de la página en vez de
	# mantener el tamaño de página definido en el PDF
	[ ! -f "$CACHE.jpg" ] &&
		gs -sDEVICE=jpeg -dUseCropBox -dFirstPage=1 -dLastPage=1 -r300 -o "$CACHE.jpg" "$1" >/dev/null

	draw "$CACHE.jpg"
	;;

# Mostar la primera página del comic
*/vnd.comicbook+zip | */vnd.comicbook-rar)
	CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$HASH"
	[ ! -f "$CACHE" ] && {
		TMP_DIR="$(mktemp -d /tmp/lf.XXXX)"
		# Obtener y extraer la 1ª imagen
		FIRST_IMAGE=$(7z l "$1" | grep "jpg\|png" | awk '{print substr($0, index($0,$6))}' | sort | head -n1)
		if [ -n "$FIRST_IMAGE" ]; then
			7z e "$1" "$FIRST_IMAGE" -o"$TMP_DIR" >/dev/null 2>&1
			mv "$TMP_DIR/$(basename "$FIRST_IMAGE")" "$CACHE"
			rm -rf "$TMP_DIR"
		fi
	}

	draw "$CACHE"
	;;

# Listar archivos y ver preview
*/x-krita)
	CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/lf/$HASH"
	PREVIEW="$CACHE_DIR/preview.png"
	FILE_LIST="$CACHE_DIR/filelist.txt"
	[ ! -d "$CACHE_DIR" ] && mkdir -p "$CACHE_DIR"
	[ ! -f "$PREVIEW" ] && 7z e "$1" preview.png -o"$CACHE_DIR" >/dev/null 2>&1
	[ ! -f "$FILE_LIST" ] && unzip -l "$1" | tee "$FILE_LIST" >/dev/null

	draw "$PREVIEW" && linebreaks "$PREVIEW"
	cat "$FILE_LIST"
	;;

*/json*) bat -fp --terminal-width "$((4 - 2))" -l JSON "$1" ;;
*/pgp-encrypted) gpg --list-packets "$1" ;;
*/postscript | */x-xpixmap | */x-xcf | */heif | */bmp) magick_convert "$1" ;;
*/vnd.rar | */zip | */vnd.android.package-archive | */x-7z-compressed) 7z l "$1" ;;
*/x-tar | */x-compressed-tar) tar -tf "$1" ;;
*opendocument*) odt2txt "$1" ;;
image/*) image "$1" ;;
*) mediainfo "$1" | tr -s " " ;;

esac

exit 1
