env = GTK_THEME,Gruvbox-Dark
env = GDK_BACKEND,wayland,x11,*

general {
	gaps_in = 12
	gaps_out = 24

	border_size = 3
	resize_on_border = false
	col.active_border = rgb(b8bb26)
	col.inactive_border = rgb(1d2021)

	layout = master
}

decoration {
	rounding = 12

	shadow {
		enabled = true
		range = 12
		render_power = 2
		color = rgb(151515)
	}

	blur {
		enabled = true
		size = 4
		passes = 2
		noise = 0.01
		contrast = 0.75
		brightness = 0.66
		vibrancy = 0.0
		vibrancy_darkness = 1.0
		special = true
	}
}

animations {
	enabled = yes
	bezier =  easeInQuart, 0.5, 0, 0.75, 0
	bezier = easeOutQuart, 0.25, 1, 0.5, 1

	animation = layers, 1, 1.5, easeOutQuart, slidefade 20%
	animation = windows, 1, 0.5, easeOutQuart, slidefade 20%
	animation = border, 0
	animation = workspaces, 1, 1.5, easeOutQuart, slide
	animation = specialWorkspace, 1, 1.5, easeOutQuart, slidevert 20%
	animation = hyprfocusIn, 1, 1, easeInQuart
	animation = hyprfocusOut, 1, 3, easeOutQuart
}


plugin {
	hyprbars {
		bar_height = 30

		col.text = rgb(ebdbb2)
		bar_text_align = center

		bar_color = rgb(1D2021)
		bar_precedence_over_border = true

		bar_buttons_alignment = left
		bar_padding = 9
		bar_button_padding = 6
		hyprbars-button = rgb(cc241d), 15, , hyprctl dispatch killactive
		hyprbars-button = rgb(d79921), 15, , hyprctl dispatch fullscreen 1
		hyprbars-button = rgb(98971a), 15, , ~/.dotfiles/bin/hyprland/switch-scratchpad

		bar_text_size = 20
		bar_text_font = Fira Sans Compressed

		bar_part_of_window = false
		bar_blur = false
	}

	hyprfocus {
		keyboard_focus_animation = slide
		slide_height = 10
	}
}
